# Generated by Django 3.2.9 on 2021-11-11 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_alter_promoter_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promoter',
            name='image',
            field=models.ImageField(upload_to='promoters/'),
        ),
    ]
